version: "3.9" # docker-composeのバージョン https://docs.docker.jp/compose/compose-file.html
services:
  app:
    build: ./infra/php
    volumes: # オプション  https://docs.docker.jp/docker-for-mac/osxfs-caching.html
      - ./src:/data
  web:
    image: nginx:1.20-alpine 
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data